---
title: perSEVERE - FRC Team 5962
timezone: UTC
collections:
  mentors:
    title: Mentors
    output: false
  posts:
    title: Posts
    output: true
  students:
    title: Students
    output: false
  tags:
    title: Tags
    output: true
    permalink: "/tags/:name/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: "/tags/"
  values:
    layout: default
- scope:
    path: ''
    type: mentors
  values:
    role: 
    order-number: 100
- scope:
    path: ''
    type: students
  values:
    role: 
    grad-year: 
    order-number: 254
permalink: "/news/:title"
description: Team 5962, also known as perSEVERE, is a FIRST Robotics Competition (FRC)
  team from Lowell, Massachusetts. Since our rookie season in 2016, we've welcomed
  middle and high school students from the Merrimack Valley and bring STEM to our
  community through many outreach events.
url: https://frcpersevere.com
nav-links:
- name: About
  url: "/about"
- name: News
  url: "/news"
- name: Robots
  url: "/robots"
- name: Outreach
  url: "/outreach"
- name: Resources
  url: "/resources"
- name: Sponsors
  url: "/sponsors"
- name: Contact
  url: "/contact"
- name: Join The Team
  url: "/join-the-team"
sass:
  style: compressed
plugins:
- jekyll/tagging
tag_page_layout: tag
tag_page_dir: "/tags"
homepage_about_text: "<p>We're Team 5962, also known as perSEVERE, a <i>FIRST</i>
  Robotics Competition (FRC) team from Lowell, Massachusetts. We welcome students
  in grades 8-12 from any school, as well as mentors from any town or company.</p><p>Every
  year, we analyze the game that <i>FIRST</i> releases and design, build, wire, and
  test a robot to compete with teams from across New England and around the world.
  We're also highly involved in our community through fundraising and outreach events!</p>"
homepage_sponsor_text: "<p>The generosity of our sponsors is crucial to our success.
  Our gold sponsors for the 2025-2026 season include Merrimack Valley Robotics, UMass
  Lowell, Mike Riendeau, the Gene Haas Foundation, Johnson Controls, Comcast, Raytheon
  Technologies, F.W. Webb, TE Connectivity, Boston Scientific, Lowell Mass Cultural
  Council, BAE Systems, NOKIA Bell Labs, Teradyne, Post-Acute Medical Services, and
  Evolv Technology. Silver sponsors include Analog Devices Foundation, Bolt Depot,
  CSS Architects, Carbon Colors, and Johnson Controls Volunteer Matching."
